version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/usr/src/qraphql
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      MONGODB_URL: mongodb://mongodb/app
  db:
    image: mongo
    container_name: mongodb
